### ISSUE TITLE
[Bug?] Token setting button too large 

### ISSUE THREAD

**Issue by uniwars** [ChasarooniZ/pf2e-rpg-numbers#42]
**Describe the bug**
Hi, when having other modules that add buttons to the token settings it will make button look weird.

**Screenshots**
![image](https://github.com/ChasarooniZ/pf2e-rpg-numbers/assets/65986545/331cb865-7b64-42f0-b0cb-a3d423d3e8fe)

Could the button be renamed "RPG" or "Crit" / "Anim" or something like that ?

**Comment by ChasarooniZ** [comment]
Will move it out entirely in refactor, but other 2 have name overlaps with other modules `rpg-numbers` etc.. but the real issue is the  token config HUD wasn't made to hold this many tabs (and many modules have a tab)

But tl;Dr data will get moved at some point but idk when I'll get time to work on it 乁⁠(⁠ ⁠⁰͡⁠ ⁠Ĺ̯⁠ ⁠⁰͡⁠ ⁠)⁠ ⁠ㄏ
